name: Transcribe AWS Podcasts (whisper.cpp + auto-fetch, resumable)

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      model:
        description: "Whisper model (base.en, small.en, medium.en)"
        required: true
        default: "small.en"
      source_name:
        description: "Name to record as 'source' (e.g., AWS Official Podcast)"
        required: true
        default: "AWS Official Podcast"
      feed_url:
        description: "RSS URL to pull MP3s (AWS Official Podcast)"
        required: false
        default: "https://d3gih7jbfe3jlq.cloudfront.net/aws-podcast-feed.xml"
      max_items:
        description: "Max episodes to pull from RSS (if provided)"
        required: false
        default: "5"

jobs:
  transcribe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/check
